//=====================================================
// This file was auto-generated by xlate_vreg v1.3
//            -->  DO NOT EDIT!  <-- 
//=====================================================
#ifndef _FPGA_REG_H
#define _FPGA_REG_H


//
// Register:    REG_LOAD_ABM_VIA_PCI
// Size:        32-bits
// Type:        Write only
// Description: Copy an ABM from host-RAM into one or both ABM buffers
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     load_0                         1       0 WO   n/a         Copy ABM from host RAM to ABM buffer #0
//     load_1                         1       1 WO   n/a         Copy ABM from host RAM to ABM buffer #1
//
#define REG_LOAD_ABM_VIA_PCI                                         0x0000000000001000ULL
#define REG_LOAD_ABM_VIA_PCI_load_0                                  0x0100000000001000ULL
#define REG_LOAD_ABM_VIA_PCI_load_1                                  0x0101000000001000ULL


//
// Register:    REG_ABM_HOST_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: Source address in host RAM for loading ABMs
//
#define REG_ABM_HOST_ADDR                                            0x4000000000001004ULL


//
// Register:    REG_SELECT_HSI
// Size:        32-bits
// Type:        Read/Write
// Description: Select HSI or SPI bus for SMEM writes
//              0 = SPI, 1 = HSI
//
#define REG_SELECT_HSI                                               0x000000000000100cULL


//
// Register:    REG_FORCE_SMEM
// Size:        32-bits
// Type:        Read/Write
// Description: Write a 1 to force all rows of the next received ABM
//              to be written to cache and SMEM.
//              Auto-clears to 0.
//
#define REG_FORCE_SMEM                                               0x0000000000001010ULL


//
// Register:    REG_CHIPIO_ADDR
// Size:        32-bits
// Type:        Read/Write
// Description: The address on the sensor chip that you wish to read or write
//
#define REG_CHIPIO_ADDR                                              0x0000000000001014ULL


//
// Register:    REG_CHIPIO_DATA
// Size:        32-bits
// Type:        Read/Write
// Description: Reading this register returns the data from the most recent
//              chip-register read or write
//              
//              Data written to this register will be written to the chip-register
//              specified by CHIPIO_ADDR when a write command is issued via CHIPIO_CMD
//
#define REG_CHIPIO_DATA                                              0x0000000000001018ULL


//
// Register:    REG_CHIPIO_CMD
// Size:        32-bits
// Type:        Read/Write
// Description: Write a command to begin a chip-register READ/WRITE:
//              1 = Read the value at chip-register address CHIPIO_ADDR
//              2 = Write CHIPIO_DATA to chip-register address CHIPIO_ADDR
//              5 = Same as 1, but auto-increments CHIPIO_ADDR by 4
//              6 = Same as 2, but auto-increments CHIPIO_ADDR by 4
//              Any other value = undefined behavior
//              
//              This register auto-clears to 0 when the read or write is complete
//
#define REG_CHIPIO_CMD                                               0x000000000000101cULL


//
// Register:    REG_SMEM_BUSY
// Size:        32-bits
// Type:        Read only
// Description: Non-zero = SMEM is being updated
//
#define REG_SMEM_BUSY                                                0x0000000000001024ULL


//
// Register:    REG_SMEM_ROWS_UPD
// Size:        32-bits
// Type:        Read only
// Description: The count of rows updated during the last SMEM update
//
#define REG_SMEM_ROWS_UPD                                            0x0000000000001028ULL


//
// Register:    REG_SMEM_WORDS_UPD
// Size:        32-bits
// Type:        Read only
// Description: The count of 32-bit words updated during the last SMEM update
//
#define REG_SMEM_WORDS_UPD                                           0x000000000000102cULL


//
// Register:    REG_ABM_COUNT
// Size:        32-bits
// Type:        Read/Write
// Description: The count of ABMs received.  Write any value to clear
//
#define REG_ABM_COUNT                                                0x0000000000001030ULL


//
// Register:    MC_RFD_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: Address of remote frame data buffer
//
#define MC_RFD_ADDR                                                  0x4000000000001100ULL


//
// Register:    MC_RFD_SIZE
// Size:        64-bits
// Type:        Read/Write
// Description: Size of remote frame data buffer
//
#define MC_RFD_SIZE                                                  0x4000000000001108ULL


//
// Register:    MC_RMD_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: Address of remote meta data buffer
//
#define MC_RMD_ADDR                                                  0x4000000000001110ULL


//
// Register:    MC_RMD_SIZE
// Size:        64-bits
// Type:        Read/Write
// Description: Size of remote meta data buffer
//
#define MC_RMD_SIZE                                                  0x4000000000001118ULL


//
// Register:    MC_RFC_ADDR
// Size:        64-bits
// Type:        Read/Write
// Description: Address where the remote frame counter should be stored
//
#define MC_RFC_ADDR                                                  0x4000000000001120ULL


//
// Register:    MC_FRAME_SIZE
// Size:        32-bits
// Type:        Read/Write
// Description: Frame size in bytes (typically 0x40_0000)
//
#define MC_FRAME_SIZE                                                0x0000000000001128ULL


//
// Register:    MC_PACKET_SIZE
// Size:        32-bits
// Type:        Read/Write
// Description: Frame data packet size (typically 0x1000)
//
#define MC_PACKET_SIZE                                               0x000000000000112cULL


//
// Register:    MC_PACKETS_PER_GROUP
// Size:        32-bits
// Type:        Read/Write
// Description: Number of packets in a transmit group (typicall 4)
//
#define MC_PACKETS_PER_GROUP                                         0x0000000000001130ULL


//
// Register:    MC_FRAME_COUNT_0
// Size:        32-bits
// Type:        Read/Write
// Description: Number of frames transmitted on channel 0
//
#define MC_FRAME_COUNT_0                                             0x000000000000113cULL


//
// Register:    MC_FRAME_COUNT_1
// Size:        32-bits
// Type:        Read/Write
// Description: Number of frames transmitted on channel 0
//
#define MC_FRAME_COUNT_1                                             0x0000000000001140ULL


//
// Register:    REG_CHIP_POWER_CTL
// Size:        32-bits
// Type:        Read/Write
// Description: Turn chip power on or off
//              1 to turn power on, 0 to turn power off
//
#define REG_CHIP_POWER_CTL                                           0x0000000000001200ULL


//
// Register:    REG_CHIP_POWER_STATE
// Size:        32-bits
// Type:        Read only
// Description: Sensor chip power on state
//              1 = The sensor chip is on
//              0 = The sensor chip is off
//              After turning power on or off, it may take as moment
//              before that is reflected in this register
//
#define REG_CHIP_POWER_STATE                                         0x0000000000001204ULL


//
// Register:    REG_CHIP_PWR_ADC
// Size:        32-bits
// Type:        Read only
// Description: Array of 32 ADC readings
//
#define REG_CHIP_PWR_ADC                                             0x0000000000001300ULL


//
// Register:    LVDS_CAL_WEN
// Size:        32-bits
// Type:        Read only
// Description: Calibration write-enable
//              This must be non-zero before writing to LVDS_CAL_WORD
//
#define LVDS_CAL_WEN                                                 0x0000000000001400ULL


//
// Register:    LVDS_CAL_WORD
// Size:        32-bits
// Type:        Read/Write
// Description: Writing to this register writes the specified calibration word to each
//              LVDS lane selected in register LVDS_CAL_MASK.  Do not write to this register
//              unless LVDS_CAL_WEN is non-zero
//              
//              Reading from this register returns the calibration word for the lane
//              selected by LVDS_LANE_SELECT
//              
//              Valid calibration words are 0 thru 4095 (i.e., 0x0000 thru 0xFFF)
//              
//              > For informational purposes only:  Bits 11:9 are a bitslip value (0 thru 7)
//              >                                   Bits  8:0 are a delay tap (0 thru 0x1FF)
//
#define LVDS_CAL_WORD                                                0x0000000000001404ULL


//
// Register:    LVDS_LANE_SELECT
// Size:        32-bits
// Type:        Read/Write
// Description: Selects the LVDS lane that will be read when reading LVDS_CAL_WORD
//              Valid values are 0 thru 63
//
#define LVDS_LANE_SELECT                                             0x0000000000001408ULL


//
// Register:    LVDS_RESET_HSSIO
// Size:        32-bits
// Type:        Read/Write
// Description: Writing a 1 to this register places the FPGA's "High Speed Serial I/O" logic
//              in reset.    Writing a 0 takes the HSSIO logic out of reset.
//
#define LVDS_RESET_HSSIO                                             0x000000000000140cULL


//
// Register:    LVDS_CLEAR_ERRORS
// Size:        32-bits
// Type:        Write only
// Description: Writing a 1 clears the error bits in LVDS_ALIGN_ERR and LVDS_PRBS_ERR
//
#define LVDS_CLEAR_ERRORS                                            0x0000000000001410ULL


//
// Register:    LVDS_FRAME_HEADER
// Size:        32-bits
// Type:        Read/Write
// Description: The four-byte frame-header pattern that the sensor-chip generates.
//              The value of this register must match the value in sensor-chip register SRDWR_HEADER_PATTERN.
//              Default value is 0x0FAA0FAA
//
#define LVDS_FRAME_HEADER                                            0x0000000000001414ULL


//
// Register:    LVDS_HDR_MATCH_BITS
// Size:        32-bits
// Type:        Read/Write
// Description: Defines the number of bits of LVDS_FRAME_HDR that must match the data in the LVDS
//              lane in order for LVDS lane data to be recognized as a frame-header.
//              Valid values are 1 thru 32.  Default value is 32.
//
#define LVDS_HDR_MATCH_BITS                                          0x0000000000001418ULL


//
// Register:    LVDS_FRAMING_ERRS
// Size:        32-bits
// Type:        Read only
// Description: Count of the number of LVDS frames in which at least one LVDS lane was
//              missing a frame header.
//              This value is cleared by a full system reset
//
#define LVDS_FRAMING_ERRS                                            0x000000000000141cULL


//
// Register:    LVDS_MAX_LANE_SKEW
// Size:        32-bits
// Type:        Read only
// Description: The maximum lane-to-lane skew measured during frame-header detection.
//              This value is cleared by a full system reset.
//
#define LVDS_MAX_LANE_SKEW                                           0x0000000000001420ULL


//
// Register:    LVDS_MISS_HDR_STATUS
// Size:        32-bits
// Type:        Read only
// Description: The status of the "missing header" registers LVDS_MISS_HDR_FRAME and
//              LVDS_MISS_HDR_LANES.  Reading this register (when it returns a 1)
//              causes valid data to be latched into the above mentioned registers
//
#define LVDS_MISS_HDR_STATUS                                         0x0000000000001424ULL


//
// Register:    LVDS_MISS_HDR_FRAME
// Size:        32-bits
// Type:        Read only
// Description: If the last read of LVDS_MISS_HDR_STATUS returned a 1, this register
//              contains the frame number of the frame that had missing frame headers
//
#define LVDS_MISS_HDR_FRAME                                          0x0000000000001428ULL


//
// Register:    LVDS_MISS_HDR_LANES
// Size:        64-bits
// Type:        Read only
// Description: If the last read of LVDS_MISS_HDR_STATUS returned a 1, this register
//              contains a bitmap of which LVDS lanes were missing headers.
//
#define LVDS_MISS_HDR_LANES                                          0x400000000000142cULL


//
// Register:    LVDS_CAL_MASK
// Size:        64-bits
// Type:        Read/Write
// Description: Determines which LVDS lanes the next write to LVDS_CAL_WORD will affect.
//
#define LVDS_CAL_MASK                                                0x4000000000001440ULL


//
// Register:    LVDS_ALIGN_ERR
// Size:        64-bits
// Type:        Read only
// Description: A bitmap of which LVDS lanes detected a failure of the LVDS alignment pattern
//              This is cleared by writing a 1 to register LVDS_CLEAR_ERRORS.
//
#define LVDS_ALIGN_ERR                                               0x4000000000001448ULL


//
// Register:    LVDS_PRBS_ERR
// Size:        64-bits
// Type:        Read only
// Description: A bitmap of which LVDS lanes detected a failure of PRBS checking
//              This is cleared by writing a 1 to register LVDS_CLEAR_ERRORS.
//
#define LVDS_PRBS_ERR                                                0x4000000000001450ULL


//
// Register:    SEMU_PATTERN_WIDTH
// Size:        32-bits
// Type:        Read only
// Description: Sensor emulation - specifies the width of the programmable pattern in bits
//
#define SEMU_PATTERN_WIDTH                                           0x0000000000001500ULL


//
// Register:    SEMU_FIFO_STAT
// Size:        32-bits
// Type:        Read only
// Description: Sensor emulation - reports the "ready" status of the pattern FIFOs
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     fifo_0                         1       0 RO   0           Is FIFO_0 ready for new data? 1 = yes, 0 = no
//     fifo_1                         1       1 RO   0           Is FIFO_1 ready for new data? 1 = yes, 0 = no
//
#define SEMU_FIFO_STAT                                               0x0000000000001504ULL
#define SEMU_FIFO_STAT_fifo_0                                        0x0100000000001504ULL
#define SEMU_FIFO_STAT_fifo_1                                        0x0101000000001504ULL


//
// Register:    SEMU_F0_COUNT
// Size:        32-bits
// Type:        Read only
// Description: Sensor emulation - How many patterns are loaded into FIFO_0?
//
#define SEMU_F0_COUNT                                                0x0000000000001508ULL


//
// Register:    SEMU_F1_COUNT
// Size:        32-bits
// Type:        Read only
// Description: Sensor emulation - How many patterns are loaded into FIFO_1?
//
#define SEMU_F1_COUNT                                                0x000000000000150cULL


//
// Register:    SEMU_ACTIVE_FIFO
// Size:        32-bits
// Type:        Read only
// Description: Sensor emulation - which FIFO is currently active?
//              The two bits can both be off, but they can never both be on
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     fifo_0                         1       0 RO   0           1 = FIFO_0 is outputting data
//     fifo_1                         1       1 RO   0           1 = FIFO_1 is outputting data
//
#define SEMU_ACTIVE_FIFO                                             0x0000000000001510ULL
#define SEMU_ACTIVE_FIFO_fifo_0                                      0x0100000000001510ULL
#define SEMU_ACTIVE_FIFO_fifo_1                                      0x0101000000001510ULL


//
// Register:    SEMU_SIM_SELECT
// Size:        32-bits
// Type:        Read/Write
// Description: Sensor emulation - Is the system in sensor emulation mode?
//              0 = LVDS data and pa_sync come from the senor chip
//              1 = LVDS data and pa_sync come from the sensor emulator
//
#define SEMU_SIM_SELECT                                              0x0000000000001514ULL


//
// Register:    SEMU_FIFO_CTL
// Size:        32-bits
// Type:        Read/Write
// Description: Sensor emulation - FIFO control : Resets (i.e., clears) the pattern FIFOs
//              >> It is not possible to reset an active FIFO <<
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     f0_reset                       1       0 RO   0           1 = Hold FIFO_0 in reset (i.e., empty it)
//     f1_reset                       1       1 RO   0           1 = Hold FIFO_1 in reset (i.e., empty it)
//
#define SEMU_FIFO_CTL                                                0x0000000000001518ULL
#define SEMU_FIFO_CTL_f0_reset                                       0x0100000000001518ULL
#define SEMU_FIFO_CTL_f1_reset                                       0x0101000000001518ULL


//
// Register:    SEMU_LOAD_F0
// Size:        32-bits
// Type:        Read/Write
// Description: Sensor emulation - Writing a value this register writes it to FIFO_0
//              Before writing a value, FIFO_STAT_fifo_0 must be 1
//
#define SEMU_LOAD_F0                                                 0x0000000000001520ULL


//
// Register:    SEMU_LOAD_F1
// Size:        32-bits
// Type:        Read/Write
// Description: Sensor emulation - Writing a value this register writes it to FIFO_1
//              Before writing a value, FIFO_STAT_fifo_1 must be 1
//
#define SEMU_LOAD_F1                                                 0x0000000000001524ULL


//
// Register:    SEMU_START
// Size:        32-bits
// Type:        Read/Write
// Description: Sensor emulation - Starts or stops frame generation
//              
//              > 0 : If a FIFO is currently active, frame generation continues until
//              >     the last frame for that FIFO has been generated, then frame generation
//              >     halts.
//              >
//              > 1 : If FIFO_1 is currently active, frame generation continues until
//              >     the last frame for that FIFO has been generated, then frame generation
//              >     continues from FIFO_0.   If FIFO_1 is not currently active, then frame
//              >     generation commences immediately from FIFO_0.
//              >
//              > 2 : If FIFO_0 is currently active, frame generation continues until
//              >     the last frame for that FIFO has been generated, then frame generation
//              >     continues from FIFO_1.   If FIFO_0 is not currently active, then frame
//              >     generation commences immediately from FIFO_1
//              >
//              > Any other value : nothing happens
//              
//              It is not possible to start frame generation from an empty FIFO
//
#define SEMU_START                                                   0x0000000000001528ULL


//
// Register:    SEMU_HARD_STOP
// Size:        32-bits
// Type:        Read/Write
// Description: Sensor emulation - Writing any value to this register causes frame generation
//              to halt immediately after the current frame (if any) has
//              been transmitted.
//
#define SEMU_HARD_STOP                                               0x000000000000152cULL


//
// Register:    CHIP_REF_CLOCK
// Size:        32-bits
// Type:        Read only
// Description: HSI clock: reference frequency in Hz.
//
#define CHIP_REF_CLOCK                                               0x0000000000009000ULL


//
// Register:    CHIP_CLOCK_VCO
// Size:        32-bits
// Type:        Read only
// Description: Chip Interface clock - VCO configuration.  See "Clock Configuration Register 0" in PG065.
//              
//              >                 REF_CLOCK * (clkfbout_mlt + clkfbout_frac/1000)
//              > VCO frequency = ------------------------------------------------
//              >                                 divclk_divide
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     divclk_divide                  8   07:00 RO   n/a         8-bit divide value of the reference clock
//     clkfbout_mult                  8   15:08 RO   n/a         Integer part of clock multiplier
//     clkfbout_frac                  10  25:16 RO   n/a         Fractional part of clock multiplier
//
#define CHIP_CLOCK_VCO                                               0x0000000000009004ULL
#define CHIP_CLOCK_VCO_divclk_divide                                 0x0800000000009004ULL
#define CHIP_CLOCK_VCO_clkfbout_mult                                 0x0808000000009004ULL
#define CHIP_CLOCK_VCO_clkfbout_frac                                 0x0a10000000009004ULL


//
// Register:    CHIP_CLOCK_DIV
// Size:        32-bits
// Type:        Read/Write
// Description: Chip interface clock - Frequency divider.  See "Clock Configuration Register 2" in PG065
//              ** Changing this value changes the frequency of the clock! **
//              
//              >                                   VCO frequency
//              >     clock frequency = ------------------------------------
//              >                       (clkout_divide + clockout_frac/1000)
//
// Fields:
//     NAME                           WID   POS TYPE RESET       DESCRIPTION
//     clkout_divide                  8   07:00 RW   n/a         Integer portion of VCO divide value
//     clkout_frac                    10  17:08 RW   n/a         Fractional portion of VCO divide value
//
#define CHIP_CLOCK_DIV                                               0x0000000000009008ULL
#define CHIP_CLOCK_DIV_clkout_divide                                 0x0800000000009008ULL
#define CHIP_CLOCK_DIV_clkout_frac                                   0x0a08000000009008ULL


//
// Register:    CHIP_FREQ_OUT
// Size:        32-bits
// Type:        Read only
// Description: The measured value of the chip interface clock, in Hz
//
#define CHIP_FREQ_OUT                                                0x000000000000900cULL



#endif
